[package]
name = "fire-http-api"
description = "Make web apis"
version = "0.2.0-rc.1"
authors = ["Sören Meier <info@s-me.ch>"]
repository = "https://github.com/fire-lib/fire-http-api"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
stream = ["fire/ws", "codegen/stream"]
## Trace logging is only enabled with this feature
trace = []

[dependencies]
serde = "1.0"
fire = { package = "fire-http", version = "0.3.0-rc.1", path = "../fire-http", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.17", features = ["macros"] }
tracing = "0.1"
codegen = { package = "fire-http-codegen", version = "0.1", path = "../fire-http-codegen", features = ["api"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
all-features = true