[package]
name = "fire-http-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[[test]]
name = "ws_route"
required-features = ["ws"]

[features]
json = []
ws = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro-crate = "1.2"

[dev-dependencies]
fire = { package = "fire-http", version = "0.3.0-rc.1", path = "../fire-http", features = ["ws", "json"] }